# Generated by Django 5.2.7 on 2025-10-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_remove_project_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                related_name="projects", to="resume.technology"
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="category",
            field=models.CharField(
                choices=[("softskill", "SoftSkill"), ("techskill", "TechSkill")],
                max_length=150,
            ),
        ),
    ]
